apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP